name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  workflow_dispatch:

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
  cargo-audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/audit@v1
