name: Build and Test
on:
  push:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Formatting
        run: cargo fmt --check
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Build dev
        run: cargo build
      - name: Test dev
        run: cargo test
      - name: Build release
        run: cargo build
      - name: Test release
        run: cargo test

